---
title: 'Report of Titanic: 2nd degree families and majority voting'
output: html_document
---
```{r}

library(knitr)
library(ggplot2)
library(dplyr)
options(stringsAsFactors = FALSE)
```


```{r}
View(iris)
iris[1,]

```

# 從檔案中讀取data
```{r}
testdata <- read.csv('./data_titanic/all/test.csv')
traindata <- read.csv('./data_titanic/all/train.csv')
```

```{r}
str(traindata)
testdata$Survived <- NA
all <- rbind(traindata, testdata)

# variables have to be the same so that can use rbind

```

```{r}
sapply(all, function(x) {sum(is.na(x))})
```

```{r}
all$Sex <- as.factor(all$Sex)
all$Survived <- as.factor(all$Survived)
all$Pclass <- as.ordered(all$Pclass)
is.na(all$Survived)
all[!is.na(all$Survived),]
```



```{r}
ggplot(all[!is.na(all$Survived),], aes(x = Survived, fill = Survived)) +
  geom_bar(stat='count') +
  labs(x = 'How many people died and survived on the Titanic?') +
        geom_label(stat='count',aes(label=..count..), size=5) +
        theme_grey(base_size = 15)
```
```{r}
p11 <- ggplot(all, aes(x = Sex, fill = Sex)) +
  geom_bar(stat='count', position='dodge') + theme_grey() +
  labs(x = 'All data') +
        geom_label(stat='count', aes(label=..count..)) +
        scale_fill_manual("legend", values = c("female" = "pink", "male" = "green"))
p11
```
# 由p2可見，性別是影響存活率重要的變項
```{r}
p1 <- ggplot(all, aes(x = Sex, fill = Sex)) +
  geom_bar(stat='count', position='stack') + theme_grey() +
  labs(x = 'All data') +
        geom_label(stat='count', aes(label=..count..)) +
        scale_fill_manual("legend", values = c("female" = "pink", "male" = "green"))
p2 <- ggplot(all[!is.na(all$Survived),], aes(x = Sex, fill = Survived)) +
  geom_bar(stat='count', position='dodge') + theme_grey() +
  labs(x = 'Training data only') +
        geom_label(stat='count', aes(label=..count..))

p1
p2
```
```{r}
p3 <- ggplot(all, aes(x = Pclass, fill = Pclass)) +
  geom_bar(stat='count', position='dodge') +
  labs(x = 'Pclass, All data') + geom_label(stat='count', aes(label=..count..)) +
   theme(legend.position="none") + theme_grey()     
p4 <- ggplot(all[!is.na(all$Survived),], aes(x = Pclass, fill = Survived)) +
  geom_bar(stat='count', position='dodge') + labs(x = 'Training data only') +
        theme(legend.position="none") + theme_grey()
p5 <- ggplot(all[!is.na(all$Survived),], aes(x = Pclass, fill = Survived)) +
  geom_bar(stat='count', position='stack') +
  labs(x = 'Training data only', y= "Count") + facet_grid(.~Sex) +
        theme(legend.position="none") + theme_grey()
p6 <- ggplot(all[!is.na(all$Survived),], aes(x = Pclass, fill = Survived)) +
  geom_bar(stat='count', position='fill') +
  labs(x = 'Training data only', y= "Percent") + facet_grid(.~Sex) +
        theme(legend.position="none") + theme_grey()
p6
```



# 將名字中間的身份地位取出，後續分析用。
# 將姓氏取出，後續分析用。
```{r}
Names <- traindata$Name
# splitTitle <- function(x){
#   strsplit(x,split='[,.]')[[1]][1]
# 
# }



traindata$Surname <- sapply(as.character(Names), function(x) {strsplit(x, split='[,.]')[[1]][1]})

traindata$Title <- sapply(as.character(Names), function(x) {strsplit(x, split='[,.]')[[1]][2]})
traindata$Title <- sub(' ', '', traindata$Title)

table <- kable(table(traindata$Sex, traindata$Title))
table

# Names[1]
# name1 <- as.character(Names)
# class(Names)
# class(name1)

# testdata$surname <- sapply(as.character(Names),splitTitle)

# Temp <- testdata$Name
# library(knitr)
# Temp <- sapply(as.character(Names),splitTitle)
# testdata$surname <- Temp
# View(Temp)
```


# title的變項很多個，把相似的變項合併，以利後續作圖。
```{r}

traindata$Title[traindata$Title %in% c("Mlle", "Ms")] <- "Miss"
traindata$Title[traindata$Title == "Mme"] <- "Mrs"
traindata$Title[!(traindata$Title %in% c('Master', 'Miss', 'Mr', 'Mrs'))] <- "Rare Title"
traindata$Title <- as.factor(traindata$Title)
table2 <- kable(table(traindata$Sex, traindata$Title))
table2

```



```{r}
ggplot(all[!is.na(traindata$Survived),], aes(x = Title, fill = Survived)) +
  geom_bar(stat='count', position='stack') +
  labs(x = 'Title') +theme_grey()
```

