---
title: "ptt_boy-girl_crawler"
output:html_notebook
anthor: Willsonyen
---

```{r}
source("pttTestFunction.R")
id = c(4043:4045)
URL = paste0("https://www.ptt.cc/bbs/NTUcourse/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)
```



```{r}
# # install.packages("tmcn")
# install.packages("NLP")
# install.packages("tm")
# install.packages("jiebaRD")
# install.packages("jiebaR")
# install.packages("wordcloud")
# install.packages("wordcloud2")

library(xml2)
library(tmcn)
library(rvest)
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(knitr)
library(wordcloud)
library(wordcloud2)
library(jiebaR)
```



```{r}
rm(list=ls(all.names = TRUE))

filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)

docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "網址")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "妳")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "但")

#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
View(docs)
class(docs)
str(docs)
```


```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
kable(head(freqFrame), format = "markdown")
```

```{r}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(6,0.5),min.freq=10,max.words=100,
          random.order=FALSE, random.color=TRUE, 
          rot.per=0, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=FALSE)
```


```{r}
wordcloud2(freqFrame[1:300,], size = 0.5,shape = 'pentagon')
```

```{r}
wordcloud2(freqFrame[1:300,], size = 0.5,shape = 'star')
```

